cicd: automating readme.md update

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -7,6 +7,8 @@ on:
 
 permissions:
   contents: write
+  pages: write
+  id-token: write
 
 jobs:
   read-version:
@@ -56,3 +58,34 @@ jobs:
           publish_dir: ${{ env.BUILD_OUTPUT_DIR }}/browser
           destination_dir: ${{ needs.read-version.outputs.app_version }}
           keep_files: true
+
+  update-readme:
+    needs: [read-version, build-and-deploy]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      # Set up Git identity for the commit
+      - name: Git Setup
+        run: |
+          git config user.name 'github-actions[bot]'
+          git config user.email 'github-actions[bot]@users.noreply.github.com'
+
+      - name: Inject Version into README Template
+        id: inject-version
+        run: |
+          VERSION="${{ needs.read-version.outputs.app_version }}"
+
+          echo "Current Version: $VERSION"
+          sed "s/VERSION-HERE/$VERSION/g" README_TEMPLATE.md > README.md
+
+      - name: Commit updated README
+        run: |
+          git add README.md
+
+          # '|| true' ensures the step doesn't fail if there are no changes to commit
+          git commit -m "docs: Update live demo link to version $VERSION [skip ci]" || true
+
+          # Push only if a commit was made
+          git push
